const seedEmails = [
  { id: 1, sender: 'Maya Chen · Northstar Labs', initials: 'MC', time: '09:42', subject: 'Invoice INV-2048 for August services', preview: 'Please find our August invoice attached. Payment terms are net 30.', body: 'Hi team,\n\nPlease find attached invoice INV-2048 for August services, totaling $4,800. Payment terms are net 30.\n\nThanks,\nMaya', intent: 'Invoice submission', intentClass: 'invoice', confidence: 98, action: 'Logged invoice INV-2048', actionDetail: 'Created an accounts-payable record for $4,800 and routed it to the Finance queue.', reasoning: 'Contains a valid invoice ID, amount, and payment terms.', auditAction: 'Invoice logged', status: 'done' },
  { id: 2, sender: 'Jordan Bell · Vertex Supply', initials: 'JB', time: '09:17', subject: 'Checking status of PO-880 payment', preview: 'Could you confirm when our outstanding payment will be released?', body: 'Hello,\n\nCould you confirm when the outstanding payment for PO-880 will be released? Our records show it is now five days overdue.\n\nRegards,\nJordan', intent: 'Payment query', intentClass: 'payment', confidence: 96, action: 'Drafted payment-status reply', actionDetail: 'Prepared a reply with the current payment status and assigned Finance as owner.', reasoning: 'Asks for the status of a specific overdue payment.', auditAction: 'Reply drafted', status: 'done' },
  { id: 3, sender: 'Alicia Romero · Brightline', initials: 'AR', time: '08:51', subject: 'Disputed charge on our July statement', preview: 'We do not recognize the $650 platform fee and need this reviewed.', body: 'Hi,\n\nWe do not recognize the $650 platform fee on our July statement. Please review the charge before our next payment run.\n\nAlicia', intent: 'Billing dispute', intentClass: 'dispute', confidence: 94, action: 'Opened dispute case #D-412', actionDetail: 'Created a billing dispute, attached the source email, and assigned the Billing Support queue.', reasoning: 'Explicitly challenges a billed amount and requests investigation.', auditAction: 'Dispute created', status: 'done' },
  { id: 4, sender: 'Promotions Desk', initials: 'PD', time: '08:30', subject: 'Unlock 300% growth with our finance toolkit', preview: 'Limited-time offer — get your free consultation today.', body: 'Unlock 300% growth with our finance toolkit. Limited-time offer — get your free consultation today.', intent: 'Spam / promotion', intentClass: 'spam', confidence: 99, action: 'Archived as spam', actionDetail: 'Removed the promotional message from the operational inbox with no external response.', reasoning: 'Promotional language with no existing account, order, or support context.', auditAction: 'Archived as spam', status: 'done' },
  { id: 5, sender: 'Priya Nair · Alto Health', initials: 'PN', time: '08:04', subject: 'Need help with the amount on our account', preview: 'The amount looks different from what we expected. Can someone help?', body: 'Hi team,\n\nThe amount on our account looks different from what we expected. Can someone help us understand it?\n\nPriya', intent: 'Needs human review', intentClass: 'review', confidence: 62, action: 'Escalated for review', actionDetail: 'Created a review task for Billing Support; no customer-facing reply was sent automatically.', reasoning: 'Could be a payment query or a billing dispute. Missing invoice, amount, and requested resolution.', auditAction: 'Human review task', status: 'review' },
  { id: 6, sender: 'Sam Patel · River & Co.', initials: 'SP', time: 'Yesterday', subject: 'Updated billing contact', preview: 'Please use this email for anything related to our invoices going forward.', body: 'Hello,\n\nPlease use this email for anything related to our invoices going forward.\n\nSam', intent: 'Account update', intentClass: 'payment', confidence: 91, action: 'Updated billing contact', actionDetail: 'Saved the sender as the preferred accounts-payable contact for River & Co.', reasoning: 'Requests a clear account-contact update without a payment or invoice task.', auditAction: 'Contact updated', status: 'done' }
];

let emails = []; let selectedId = null; let processed = false;
const $ = (id) => document.getElementById(id);
const sleep = (ms) => new Promise(resolve => setTimeout(resolve, ms));

function renderList() { $('emailList').innerHTML = emails.map(email => `<button class="email-card ${selectedId === email.id ? 'selected' : ''} ${email.processed ? 'done' : ''}" data-id="${email.id}" type="button"><span class="unread-dot"></span><span><span class="sender">${email.sender}</span><span class="email-subject">${email.subject}</span><span class="email-preview">${email.preview}</span>${email.processed ? `<span class="intent-pill ${email.intentClass}">${email.intent}</span>` : ''}</span><span class="email-time">${email.time}</span></button>`).join('');
  document.querySelectorAll('.email-card').forEach(card => card.addEventListener('click', () => { selectedId = Number(card.dataset.id); renderList(); renderDetail(); }));
  $('queueCount').textContent = emails.filter(e => !e.processed).length;
}
function renderDetail() { const email = emails.find(e => e.id === selectedId); if (!email) return; $('detailTitle').textContent = email.subject; const state = $('decisionState'); state.textContent = email.processed ? (email.status === 'review' ? 'Needs review' : 'Actioned') : 'Awaiting agent'; state.className = `decision-state ${email.processed ? (email.status === 'review' ? 'review' : 'completed') : ''}`;
  $('detailContent').className = 'decision-content'; $('detailContent').innerHTML = `<div class="email-meta"><span class="avatar">${email.initials}</span><span><strong>${email.sender}</strong><br><span>${email.time} · Inbox email</span></span></div><div class="email-body">${email.body}</div>${email.processed ? `<div class="decision-grid"><div class="decision-box"><span class="label">Detected intent</span><strong>${email.intent}</strong><p>${email.reasoning}</p></div><div class="decision-box"><span class="label">Confidence</span><strong>${email.confidence}%</strong><div class="confidence-bar"><i style="width:${email.confidence}%"></i></div></div></div><div class="action-card ${email.status === 'review' ? 'review-action' : ''}"><span class="label">${email.status === 'review' ? 'Safe fallback' : 'Autonomous action'}</span><strong>${email.action}</strong><p>${email.actionDetail}</p></div>` : `<div class="empty-state"><div class="empty-icon">→</div><h3>Queued for analysis</h3><p>This email will be classified and actioned when the agent runs.</p></div>`}`;
}
function updateMetrics() { const done = emails.filter(e => e.processed); $('processedMetric').textContent = `${done.length} / ${emails.length}`; $('actionMetric').textContent = done.filter(e => e.status === 'done').length; $('reviewMetric').textContent = done.filter(e => e.status === 'review').length; $('auditMetric').textContent = done.length; }
function renderAudit() { const done = emails.filter(e => e.processed); $('auditBody').innerHTML = done.length ? done.map((e,i) => `<tr class="${e.status === 'review' ? 'review-row' : ''}"><td>10:${String(3+i).padStart(2,'0')}</td><td>${e.sender.split(' · ')[0]}</td><td><span class="audit-intent ${e.intentClass}">${e.intent}</span></td><td class="audit-action">${e.auditAction}</td><td class="confidence">${e.confidence}%</td></tr>`).join('') : '<tr class="no-audit"><td colspan="5">Run the agent to create an immutable decision trail.</td></tr>'; }
async function processAll() { if (processed) return; const button = $('processButton'); button.disabled = true; button.textContent = 'Agent working…'; $('runStatus').textContent = 'Classifying inbox'; $('runSubtext').textContent = 'Analyzing intent and selecting safe actions'; for (const email of emails) { await sleep(420); email.processed = true; selectedId = email.id; renderList(); renderDetail(); updateMetrics(); renderAudit(); } processed = true; button.textContent = 'Queue complete ✓'; $('runStatus').textContent = 'Inbox actioned'; $('runSubtext').textContent = '5 actions completed · 1 safely escalated'; }
function reset() { emails = seedEmails.map(e => ({...e, processed:false})); selectedId = null; processed = false; $('processButton').disabled = false; $('processButton').innerHTML = 'Run agent <span aria-hidden="true">→</span>'; $('runStatus').textContent = 'Ready to process'; $('runSubtext').textContent = '6 emails waiting in the inbox'; $('detailTitle').textContent = 'Select an email'; $('decisionState').textContent = 'Waiting'; $('decisionState').className = 'decision-state'; $('detailContent').className = 'empty-state'; $('detailContent').innerHTML = '<div class="empty-icon">✦</div><h3>Inbox is ready</h3><p>Choose an email to inspect it, or run the agent to classify and action the entire queue.</p>'; renderList(); updateMetrics(); renderAudit(); }
$('processButton').addEventListener('click', processAll); $('resetButton').addEventListener('click', reset); reset();
